echo " "
echo "'COSMOS_SimpleFormat' is executed"
./COSMOS_SimpleFormat -volumeTitle test -volumeID 1000 -device test1.vol 500 -device test2.vol 400
echo " "
echo "'test1.vol' and 'test2.vol' is created"
echo " "
echo "=================================="
echo " "
echo "'COSMOS_CreateRelation' is executed using file 'createRelation.dat'"
echo " "
./COSMOS_CreateRelation test1.vol test2.vol < createRelation.dat
echo " "
echo " "
echo "New relation 'testRelation' is created"
echo " "
echo "=================================="
echo " "
echo "'COSMOS_InsertTuple' is executed using file 'insertTuple1.dat'"
echo " "
./COSMOS_InsertTuple test1.vol test2.vol < insertTuple1.dat
echo " "
echo " "
echo "A tuple is inserted"
echo " "
echo "=================================="
echo " "
echo "'COSMOS_InsertTuple' is executed using file 'insertTuple2.dat'"
echo " "
./COSMOS_InsertTuple test1.vol test2.vol < insertTuple2.dat
echo " "
echo " "
echo "A tuple is inserted"
echo " "
echo "=================================="
echo " "
echo "'COSMOS_PrintRelation' is executed using file 'printRelation.dat'"
echo " "
./COSMOS_PrintRelation test1.vol test2.vol < printRelation.dat
